[package]
name = "block_trie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = "3.1.2"
chrono = "0.4.19"
sp-trie = "6.0.0"
hex-literal = "0.3.4"
sp-runtime = "6.0.0"
